// Hebrew UI labels for the dashboard quick-action dialogs. Pure string map,
// lifted out of DashboardActions to keep the component focused on behaviour.
export const HEBREW = {
  saveErrorUnknown: "שגיאה לא ידועה",
  cancel: "ביטול",
  saving: "שומר...",
  customerFallback: "לקוח",
  selectCustomer: "בחרו לקוח",
  selectProject: "בחרו פרויקט",
  orderNew: "הזמנה חדשה",
  orderQuickOpen: "פתיחת טופס הזמנה מהירה",
  orderDialogDescription:
    "פתיחת הזמנה מתוך הדשבורד בלי מעבר למסך המכירות.",
  orderSaved: "ההזמנה נשמרה",
  projectNew: "פרויקט חדש",
  projectQuickCreate:
    "יצירה מהירה בלי לעזוב את הדשבורד",
  projectDialogDescription:
    "טופס קצר לפתיחה מהירה של פרויקט חדש.",
  projectName: "שם פרויקט",
  customer: "לקוח",
  projectType: "סוג פרויקט",
  logistics: "לוגיסטיקה",
  moving: "הובלה",
  construction: "שיפוצים",
  status: "סטטוס",
  statusQuote: "הצעת מחיר",
  statusPlanned: "מתוכנן",
  statusActive: "פעיל",
  statusOnHold: "בהמתנה",
  statusCompleted: "הושלם",
  statusCancelled: "בוטל",
  basePrice: "מחיר בסיס",
  projectManager: "מנהל פרויקט",
  unassigned: "ללא שיוך",
  startDate: "תאריך התחלה",
  endDate: "תאריך סיום",
  notes: "הערות",
  saveProject: "שמירת פרויקט",
  projectRequired:
    "יש לבחור לקוח ולמלא שם פרויקט.",
  projectCreateFailed: "יצירת הפרויקט נכשלה.",
  projectSaved: "הפרויקט נשמר",
  taskNew: "משימה חדשה",
  taskQuickAssign:
    "שיוך מהיר לפרויקט קיים",
  taskDialogDescription:
    "פתיחה מהירה של משימה ושיוך לפרויקט קיים.",
  project: "פרויקט",
  subject: "נושא",
  dueDate: "תאריך יעד",
  assignee: "אחראי",
  selectAssignee: "בחרו אחראי",
  saveTask: "שמירת משימה",
  taskRequired:
    "יש לבחור פרויקט, אחראי, תאריך יעד ונושא.",
  taskCreateFailed: "יצירת המשימה נכשלה.",
  taskSaved: "המשימה נשמרה",
  thisWeek: "מה יש השבוע",
  thisWeekOpen:
    "מעבר מהיר לפרויקטים ולעבודה הקרובה",
  ordersByCity: "אספקת הזמנה",
  ordersByCityOpen:
    "מעבר לרשימת משלוחים כדי לבחור הזמנה לאישור",
  expenseNew: "הוצאה חדשה",
  expenseQuickRegister: "רישום הוצאה לפי תחום",
  expenseDialogDescription:
    "רישום הוצאה חדשה לפי תחום, עם שיוך לפרויקט, הזמנה או נכס לפי הצורך.",
  amount: "סכום",
  date: "תאריך",
  category: "קטגוריה",
  selectCategory: "בחרו קטגוריה",
  otherCategoryPrompt: "מה הקטגוריה?",
  description: "תיאור",
  includedInBase: "נכלל בבסיס",
  billedToCustomer: "לחיוב לקוח",
  includesVat: "כולל מע״מ 18%",
  saveExpense: "שמירת הוצאה",
  expenseRequired:
    "יש למלא את כל שדות החובה.",
  expenseInvalidAmount: "יש להזין סכום הוצאה תקין.",
  expenseCreateFailed: "הוספת ההוצאה נכשלה.",
  expenseSaved: "ההוצאה נשמרה",
  incomeNew: "הכנסה חדשה",
  transferNew: "העברה / שיוך כפול",
  // Moving money between our own accounts (cash withdrawal / bank→bank). Not
  // "העברה" on its own — that already reads as the bank-transfer payment method.
  transferBetweenAccounts: "העברה בין חשבונות",
  incomeQuickRegister: "רישום הכנסה",
  incomeDialogDescription:
    "רישום הכנסה חדשה לתזרים, עם אפשרות לקשר לפרויקט, הזמנה או נכס.",
  paymentMethod: "אמצעי תשלום",
  paymentDueDate: "תאריך פירעון",
  bankTransfer: "העברה בנקאית",
  cash: "מזומן",
  check: "צ'ק",
  creditCard: "כרטיס אשראי",
  other: "אחר",
  reference: "אסמכתא",
  saveIncome: "שמירת הכנסה",
  incomeRequired:
    "יש למלא תאריך ואמצעי תשלום.",
  incomeInvalidAmount: "יש להזין סכום הכנסה תקין.",
  incomeCreateFailed: "הוספת ההכנסה נכשלה.",
  incomeSaved: "ההכנסה נשמרה",
  // No self-session strings here any more: opening your own shift from a quick
  // action was removed 2026-08-16 (every logged shift goes through the approval
  // queue via "דיווח נוכחות"). /profile still has the button, with its own text.
  manualSessionNew: "הוספת משמרת ידנית",
  manualSessionHint: "רישום משמרת סגורה מהדשבורד",
  manualSessionDescription:
    "הזנת משמרת ידנית עם שעת התחלה וסיום.",
  worker: "עובד",
  selectWorker: "בחרו עובד",
  domain: "תחום",
  clockIn: "שעת התחלה",
  totalHours: "סה״כ שעות",
  clockOut: "שעת סיום",
  saveManualSession: "שמירת משמרת",
  manualSessionSaved: "המשמרת נשמרה",
  manualSessionFailed: "שמירת המשמרת נכשלה.",
  sessionInvalidWorker: "יש לבחור עובד.",
  sessionInvalidProject: "יש לבחור פרויקט לתחום פרויקטים.",
  sessionInvalidProperty: "יש לבחור נכס לתחום ניהול נכסים.",
  sessionInvalidTimes: "שעת הסיום חייבת להיות אחרי שעת ההתחלה.",
} as const;
